### ISSUE TITLE
self-service-password_1.0-2_all.deb : url changed

### ISSUE THREAD

**Issue by paulz1** [grams/docker-LTB-self-service-password#3]
At first, thank you for your job.

We use your docker in our service and it works very well.

But... today, I would like to rebuild you image, and found that it does nto work now.
The problem is that url of self-service-password_1.0-2_all.deb, so the line 9 of your Docker file :
`RUN curl http://tools.ltb-project.org/attachments/download/892/self-service-password_1.0-2_all.deb > self-service-password.deb && dpkg -i self-service-password.deb ; rm -f self-service-password.deb`
is not valid actually.

The correct url now is `https://ltb-project.org/archives/self-service-password_1.0-2_all.deb`

You could hit it also as http, but in this case you should add -L option to your curl. Because http link is just "moved permanently" redirect.

**Comment by grams** [comment]
Hi,

Thank you for this feedback.

This Dockerfile was written for my previous job, I don't need/use it anymore. That's why build errors will most surely go unnoticed. I'll try to fix this.

In the meantime, don't hesitate to sumbit pull requests or even ask to be given collaborator access!

Guillaume
